server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://60.167.124.119:3306/itaim?serverTimezone=Asia/Shanghai&autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: itaim
    password: CHen12!#03
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
